name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  envied: ^1.0.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  luthor: ^0.4.4
  shadcn_ui: ^0.16.3

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  injectable_generator: ^2.6.2
  lint: ^2.3.0
  luthor_generator: ^0.5.0

flutter:
  uses-material-design: true
