name: backend
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  arcade: ^0.2.4+1
  dart_jsonwebtoken: ^2.14.2
  envied: ^1.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  goose: ^0.2.0
  hashlib: ^1.21.1
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  luthor: ^0.4.4
  postgres: ^3.4.7
  superclass: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.14
  envied_generator: ^1.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  lint: ^2.3.0
  luthor_generator: 0.5.0
  superclass_generator: ^0.2.0
